name: very_good_slide_puzzle
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  dio: ^4.0.4
  image: ^3.1.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  injectable: ^1.5.0
  intl: ^0.17.0
  url_launcher: ^6.0.20
  flutter_staggered_grid_view: ^0.6.1
  octo_image: ^1.0.0+1
  cached_network_image: ^3.2.0
  flash: ^2.0.3+2
  path_provider: ^2.0.9
  collection: ^1.15.0
  get_it: ^7.2.0
  flutter_spinkit: ^5.1.0
  auto_size_text: ^3.0.0
  html: ^0.15.0
  universal_io: ^2.0.4
  flutter_tts: ^3.3.3
  sliding_up_panel: ^2.0.0+1
  lottie: ^1.2.2
  flutter_svg: ^1.0.3
  share_plus: ^4.0.3

dev_dependencies:
  build_runner: ^2.1.8 # flutter pub run build_runner build --delete-conflicting-outputs
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1
  flutter_lints: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
